### ISSUE TITLE
awsauthenticationlib and Control Tower leads to Exception

### ISSUE THREAD

**Issue by s0enke** [schubergphilis/awsauthenticationlib#5]
Hi,

I tried out awsauthenticationlib with Control Tower. Here is my code sample:

```
import json
import copy
import logging

import http.client

http.client.HTTPConnection.debuglevel = 1

logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True

from awsauthenticationlib import (AwsAuthenticator,
                                  LoggerMixin,
                                  Urls)

def get_api_payload(content_string,
                    target,
                    region,
                    method='POST',
                    params=None,
                    path='/',
                    content_type='application/x-amz-json-1.1',
                    x_amz_target='',
                    ):
    """Generates the payload for calling the AWS SSO APIs.
    Returns:
        payload (dict): Returns a deepcopy object of the payload
    """
    payload = {'contentString': json.dumps(content_string),
               'headers': {'Content-Type': content_type,
                           'X-Amz-Target': x_amz_target,
                           'X-Amz-User-Agent': "aws-sdk-js/2.528.0 promise"},
               'method': method,
               'operation': target,
               'params': params or {},
               'path': path,
               'region': region}
    return copy.deepcopy(payload)

arn = 'arn:aws:iam::REDACTED:role/AdministratorSelfAccess'
aws_authenticator = AwsAuthenticator(arn)
print(aws_authenticator.region)



service = 'controltower'
url = f'{aws_authenticator.urls.regional_console}/{service}/home/landing?region={aws_authenticator.region}'

session = aws_authenticator._get_authenticated_session(service, url)

payload = get_api_payload(content_string={"HomeRegion": "eu-west-1",
                                          "LogAccountEmail": "REDACTED",
                                          "SecurityAccountEmail": "REDACTED"},
                          target='setupLandingZone',
                          path='/',
                          x_amz_target='AWSBlackbeardService.SetupLandingZone',
                          region=aws_authenticator.region,

                          )
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True

response = session.post('https://eu-west-1.console.aws.amazon.com/controltower/api/controltower', json=payload)
```

With this code I end up getting this exception:

```
DEBUG:urllib3.connectionpool:https://eu-west-1.console.aws.amazon.com:443 "GET /controltower/home/landing?region=eu-west-1&state=hashArgs&isauthcode=true&code=REDACTED
DEBUG:awsauthenticationlib.AwsAuthenticator:Getting url :None
Traceback (most recent call last):
  File "awsauth.py", line 52, in <module>
    session = aws_authenticator._get_authenticated_session(service, url)
  File "/Users/soenke.ruempler/Projects/founopticum/venv/lib/python3.7/site-packages/awsauthenticationlib/awsauthenticationlib.py", line 351, in _get_authenticated_session
    dashboard = self._authenticate(url, domain=service)
  File "/Users/soenke.ruempler/Projects/founopticum/venv/lib/python3.7/site-packages/awsauthenticationlib/awsauthenticationlib.py", line 329, in _authenticate
    ('seance', host)])
  File "/Users/soenke.ruempler/Projects/founopticum/venv/lib/python3.7/site-packages/awsauthenticationlib/awsauthenticationlib.py", line 299, in _get_response
    response = requests.get(**arguments)
  File "/Users/soenke.ruempler/Projects/founopticum/venv/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/soenke.ruempler/Projects/founopticum/venv/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/soenke.ruempler/Projects/founopticum/venv/lib/python3.7/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/Users/soenke.ruempler/Projects/founopticum/venv/lib/python3.7/site-packages/requests/sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/soenke.ruempler/Projects/founopticum/venv/lib/python3.7/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/Users/soenke.ruempler/Projects/founopticum/venv/lib/python3.7/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```

Any ideas?

**Comment by costastf** [comment]
@s0enke I just saw this issue! Not sure what happened there and why I did not get notified for this. I just uploaded version 0.2.0 that implements the session for control tower so you can use that. Pretty soon i will release a controltowerlib that actually uses that and can do almost anything you can do with control tower, so if you can wait for a few days you might get things working out of the box for you :). Apologies for missing this for so long.

**Comment by s0enke** [comment]
@costastf that's awesome news. This would allow us to get rid of our workaround (setting up Control Tower with Puppeteer/CWS canaries: https://github.com/superwerker/superwerker/blob/42aa3206009e824f37c1e7f3914f8da0428ab115/components/control-tower.yaml#L37-L139)

**Comment by costastf** [comment]
https://pypi.org/project/controltowerlib/ has version v0.1.0 of the library although it does not actually set up control tower, just provides an api over its usage. Contributions are welcome though :) I will definitely check out your project too! Thanks! @s0enke

**Comment by costastf** [comment]
@s0enke would you like to use keybase https://keybase.io/docs/extension to connect and have a chat at some point?
